"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('ENVIRONMENT') == 'production':
        raise ImproperlyConfigured(
            "SECRET_KEY must be set in production. "
            "Generate a secure key: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )
    # Development: use a reasonable default (NOT for production!)
    from django.core.management.utils import get_random_secret_key
    SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# Production security: Ensure not using wildcard in production
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "Cannot use wildcard '*' in ALLOWED_HOSTS for production. "
        "Set ALLOWED_HOSTS environment variable to your domain(s)."
    )

# Test mode - disable rate limiting for tests
TESTING = "test" in __import__("sys").argv


# Application definition
# Check for optional packages
import importlib.util

_HAS_JAZZMIN = importlib.util.find_spec("jazzmin") is not None
_HAS_AXES = importlib.util.find_spec("axes") is not None

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Channels: WebSocket / Realtime notifications
    "channels",

    # CORS support for frontend
    "corsheaders",

    "rest_framework",
    # Simple JWT token blacklist
    "rest_framework_simplejwt.token_blacklist",
]

# Add optional admin UI
if _HAS_JAZZMIN:
    INSTALLED_APPS.append("jazzmin")

# Add optional brute-force protection
if _HAS_AXES:
    INSTALLED_APPS.append("axes")

INSTALLED_APPS.append("core")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
]

# Add axes middleware if installed (must come before AuthenticationMiddleware)
if _HAS_AXES:
    MIDDLEWARE.append("axes.middleware.AxesMiddleware")

MIDDLEWARE.extend([
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # custom rate‑limit middleware; must come after AuthenticationMiddleware
    "core.middleware.RateLimitMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Permissions-Policy header for admin panel inline scripts
    "core.middleware.PermissionsPolicyMiddleware",
])

# SimpleJWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
    # Token refresh in HttpOnly cookie (secure XSS/CSRF protection)
    "AUTH_COOKIE": "refresh_token",
    "AUTH_COOKIE_SECURE": not DEBUG,  # HTTPS only in production
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SAMESITE": "Lax",
}

# CORS - allow all origins for development
from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'idempotency-key',
    'x-request-id',
]

# Cookie settings for refresh token
SESSION_COOKIE_SECURE = False  # set to True in production (HTTPS)
CSRF_COOKIE_SECURE = False     # set to True in production (HTTPS)
CSRF_COOKIE_SAMESITE = 'Lax'
# HttpOnly flag for refresh token cookie (prevents XSS token theft)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Axes (brute-force protection) settings - only if installed
if _HAS_AXES:
    AXES_ENABLED = True
    AXES_FAILURE_LIMIT = 5
    AXES_COOLOFF_TIME = timedelta(minutes=30)
    AXES_LOCKOUT_CALLABLE = None

# Jazzmin UI settings - only if installed
if _HAS_JAZZMIN:
    JAZZMIN_SETTINGS = {
        "site_title": "ArenaGo Admin",
        "site_header": "ArenaGo",
        "site_brand": "ArenaGo",
        "welcome_sign": "ArenaGo administration",
        "show_ui_builder": False,
    }


ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL prefix must start with a slash; previous value without leading
# slash caused admin assets to be requested from relative paths which
# made the interface appear blank.  '/static/' is the sane default.
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production collectstatic
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email configuration: default to real SMTP for production-like behavior.
# For development fall back to console if no SMTP credentials are provided.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@arenago.uz')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# For local development without SMTP set explicitly, fallback to console backend
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ============================================================================
# ESKIZ SMS GATEWAY CONFIGURATION (Uzbekistan)
# ============================================================================
ESKIZ_EMAIL = os.environ.get('ESKIZ_EMAIL', '')
ESKIZ_PASSWORD = os.environ.get('ESKIZ_PASSWORD', '')
ESKIZ_FROM_ID = os.environ.get('ESKIZ_FROM_ID', '4546')
OTP_ALLOW_MISSING_SMS_PROVIDER = os.environ.get('OTP_ALLOW_MISSING_SMS_PROVIDER', 'False').lower() in ('true', '1', 'yes')

# ============================================================================
# CLICK PAYMENT GATEWAY CONFIGURATION
# ============================================================================
CLICK_MERCHANT_ID = os.environ.get('CLICK_MERCHANT_ID', '')
CLICK_MERCHANT_SECRET = os.environ.get('CLICK_MERCHANT_SECRET', '')
CLICK_MERCHANT_USER = os.environ.get('CLICK_MERCHANT_USER', '')
CLICK_MERCHANT_PASSWORD = os.environ.get('CLICK_MERCHANT_PASSWORD', '')

# support contact defaults (used by /support/info/ endpoint)
SUPPORT_EMAIL = 'support@arenago.example'
SUPPORT_PHONE = '+998901234567'

# Security detector settings (tunable)
SECURITY_REQUEST_THRESHOLD = 200  # requests per window before alert
SECURITY_WINDOW_SECONDS = 60
SECURITY_ALERT_COOLDOWN = 3600  # don't alert again for same IP within this many seconds
SECURITY_NOTIFY_ADMINS = True

# paths to skip rate limiting in SecurityMiddleware (regexes matched against request.path)
SECURITY_EXEMPT_PATHS = [
    r'^/payment/click/webhook/$',  # external payment provider webhook
    r'^/admin/',                   # admin interface should never be rate-limited
    r'^/test/',                    # our manual testing pages
]

# new rate-limit configuration for RateLimitMiddleware
RATE_LIMIT_EXEMPT_PATHS = [
    r'^/admin/',
    r'^/support/agent/',
    r'^/static/',
    r'^/media/',
    r'^/payment/click/webhook/',
    r'^/api/auth/',  # Exempt all auth endpoints from rate limiting
] + (
    [r'^/api/'] if TESTING else []  # Disable rate limiting for tests
)
# prefixes that identify public API endpoints to be limited; leave empty to
# treat every non-exempt path as public.
RATE_LIMIT_PUBLIC_PREFIXES = [
    # e.g. '/api/', '/support/', etc.
    '/api/auth/',
]
RATE_LIMIT_WINDOW_SECONDS = 60    # seconds per bucket
RATE_LIMIT_MAX_REQUESTS = 60      # max requests per IP per bucket

# configuration for automatic banning of repeat offenders
# number of rate-limit violations before an IP is auto‑banned
AUTO_BAN_THRESHOLD = 5
# number of seconds to ban the offending IP
AUTO_BAN_SECONDS = 300

# django-axes settings (bruteforce protection)
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_ONLY_USER_FAILURES = False
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_USE_USER_AGENT = True

# Note: django-axes stores data in cache/db; for production use a shared cache (Redis/Memcached)


# Channels ASGI application and channel layer (in-memory for development)
ASGI_APPLICATION = "blog.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}




JAZZMIN_SETTINGS = {

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the library",

    # Copyright on the footer
    "copyright": "Acme Library Ltd",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["auth.User", "auth.Group"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

def _is_support_agent(user):
    return user.is_active and user.groups.filter(name="support").exists()


# Django REST Framework configuration
REST_FRAMEWORK = {
    # Default authentication method for API
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Default permission policy (most restrictive by default)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Pagination settings
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # Default filter backends
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # API documentation
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Error responses
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    # Disable strict versioning for easier development
    # 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
}


















