# Generated by Django 4.2.10 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketitem",
            name="available",
        ),
        migrations.AlterField(
            model_name="ticketitem",
            name="price_coins",
            field=models.PositiveIntegerField(),
        ),
    ]
