# Generated by Django 4.2.10 on 2026-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_ticketitem_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("discount_10", "10% Discount"),
                    ("discount_20", "20% Discount"),
                    ("discount_50", "50% Discount"),
                    ("free_field", "Free Field"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticketitem",
            unique_together={("config", "type")},
        ),
    ]
