# Generated by Django 4.2.10 on 2026-02-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_otpcode_fieldcard_admin_note_fieldcard_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
