# Generated by Django 4.2.10 on 2026-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldcard",
            name="length_m",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldcard",
            name="width_m",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
