# Generated by Django 4.2.10 on 2026-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_amenity_id_alter_booking_id_alter_fieldcard_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_fee",
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name="booking",
            name="subtotal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
