# Generated by Django 4.2.10 on 2026-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_booking_service_fee_booking_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="owner_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="platform_fee",
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service_fee",
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
