# Generated by Django 4.2.10 on 2026-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_booking_owner_amount_booking_platform_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
