# Generated by Django 4.2.10 on 2026-02-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_booking_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserved_slots",
                        to="core.booking",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="core.fieldcard",
                    ),
                ),
            ],
            options={
                "unique_together": {("field", "date", "start_time")},
            },
        ),
    ]
