# Generated by Django 4.2.10 on 2026-02-26 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_booking_payment_expires_at_supportticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
