# Generated by Django 4.2.10 on 2026-02-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_supportmessage_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
