# Generated by Django 4.2.10 on 2026-03-04 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0019_securityincident"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("attempt", "Attempt"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("cancel", "Cancel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("ip", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="otpcode",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["phone", "created_at"], name="core_otpcod_phone_ab4371_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("field", "date", "start_time"), name="uniq_field_slot"
            ),
        ),
        migrations.AddField(
            model_name="idempotencykey",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="idempotencykey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idempotency_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookinglog",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookinglog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
