# Generated by Django 4.2.10 on 2026-03-04 15:14

from django.db import migrations
import uuid


def populate_phone_field(apps, schema_editor):
    """Populate phone field with unique values for existing records with NULL phone."""
    UserProfile = apps.get_model("core", "UserProfile")
    
    for profile in UserProfile.objects.filter(phone__isnull=True):
        # Generate unique placeholder phone
        profile.phone = f"+placeholder-{uuid.uuid4().hex[:10]}"
        profile.save()


def reverse_populate_phone_field(apps, schema_editor):
    """Reverse: set phone back to NULL for migration rollback."""
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.filter(phone__startswith="+placeholder-").update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_bookinglog_idempotencykey_otpcode_attempts_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_phone_field, reverse_populate_phone_field),
    ]
