# Generated by Django 4.2.10 on 2026-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_populate_phone_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
