# Generated by Django 4.2.10 on 2026-03-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0022_make_phone_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=19)),
                ("expiry_date", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
