# Generated by Django 4.2.10 on 2026-03-28 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0023_ownercard"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("total_earned", models.BigIntegerField(default=0)),
                ("total_withdrawn", models.BigIntegerField(default=0)),
                ("total_refunded", models.BigIntegerField(default=0)),
                ("last_payout_at", models.DateTimeField(blank=True, null=True)),
                ("next_payout_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Owner Wallets",
            },
        ),
        migrations.AlterModelOptions(
            name="platformbalance",
            options={"ordering": ["-date"], "verbose_name_plural": "Platform Balances"},
        ),
        migrations.RemoveField(
            model_name="otpcode",
            name="code",
        ),
        migrations.RemoveField(
            model_name="platformbalance",
            name="total_earnings",
        ),
        migrations.AddField(
            model_name="booking",
            name="verification_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="verification_code_hash",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="verification_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="code_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="average_booking_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="date",
            field=models.DateField(db_index=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="failed_payments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="refunded_payments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="revenue_by_click",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="revenue_by_payme",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="successful_payments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="total_bookings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="total_fees",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="total_payouts",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbalance",
            name="total_revenue",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="verification_code",
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("bank_account", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="core.ownerwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("ip_address", models.CharField(db_index=True, max_length=45)),
                ("request_count", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("window_start", models.DateTimeField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone", "-window_start"],
                        name="core_otprat_phone_1aec74_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-window_start"],
                        name="core_otprat_ip_addr_d77b31_idx",
                    ),
                ],
                "unique_together": {("phone", "ip_address", "window_start")},
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.booking",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "status"],
                        name="core_webhoo_provide_f2432e_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_webhoo_created_031a8d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_price", models.PositiveIntegerField()),
                ("service_fee", models.PositiveIntegerField()),
                ("total_paid_by_user", models.PositiveIntegerField()),
                ("owner_share", models.PositiveIntegerField()),
                ("platform_share", models.PositiveIntegerField()),
                ("paid_to_owner", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission",
                        to="core.booking",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "paid_to_owner"],
                        name="core_commis_owner_i_45c6ba_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_commis_created_7c9671_idx"
                    ),
                ],
            },
        ),
    ]
