# Generated by Django 4.2.10 on 2026-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_ownerwallet_alter_platformbalance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="platform_fee",
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service_fee",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
