# Generated by Django 4.2.10 on 2026-03-29 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0025_alter_booking_platform_fee_alter_booking_service_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_used",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ten", "10%"),
                    ("twenty", "20%"),
                    ("fifty", "50%"),
                    ("free", "100%"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_ten", models.PositiveIntegerField(default=0)),
                ("tickets_twenty", models.PositiveIntegerField(default=0)),
                ("tickets_fifty", models.PositiveIntegerField(default=0)),
                ("tickets_free", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Tickets",
            },
        ),
    ]
