# Generated by Django 6.0.3 on 2026-04-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_booking_ticket_used_userticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownercard",
            name="cvv",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name="FieldImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="field_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.fieldcard",
                    ),
                ),
            ],
        ),
    ]
